---
- name: Install and Start nginx
  hosts: all
  become: true
  become_user: root  # replace with the desired user

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
    - name: Start nginx
      service:
        name: nginx
        state: started
